name: CI-CD-Prod

on:
  push:
    branches: [main]

jobs:
  prod-pipeline:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # Uses caching to make the Java setup almost instant after the first run
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle' # Helps if you have complex dependencies

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip' # Speeds up pyspark installation

      - name: Install Tools
        run: |
          pip install pytest pyspark
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: 1. Validate (Unit Tests)
        run: pytest tests/

      - name: 2. Validate (Bundle Config)
        run: databricks bundle validate -t production

      - name: 3. Deploy
        run: databricks bundle deploy -t production

      - name: 4. Run
        run: databricks bundle run transport_pipeline -t production